name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:

      - name: Create Folder for certificates and profiles
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mkdir -p ~/Library/MobileDevice/Certificates/
        
        # decode and save the p12 and provisioning files stored as secrets
      - name: Get Certificate
        id: certFileDecode
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: 'certificate.p12'
          encodedString: ${{ secrets.P12_BASE64 }}

      - name: Copy Certificate
        run: mv ${{ steps.certFileDecode.outputs.filePath }} ~/Library/MobileDevice/Certificates/certificate.p12
    
      - name: Get Profile
        id: profFileDecode
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: 'decoded.mobileprovision'
          encodedString: ${{ secrets.MOBILEPROVISION_BASE64 }}

      - name: Copy Profiles
        run: mv ${{ steps.profFileDecode.outputs.filePath }} ~/Library/MobileDevice/Provisioning\ Profiles/decoded.mobileprovision

#install the necessary dependencies
      - name: Install python and codemagic tools
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'          
          
      - name: Install python dependencies
        run:  python -m pip install codemagic-cli-tools

      - name: Setup SSH
        run: |
          mkdir -p "$HOME/.ssh"
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 "$HOME/.ssh/id_rsa"
          ssh-keyscan codeup.aliyun.com >> "$HOME/.ssh/known_hosts"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone target repo
        run: git clone --recursive "$MAINURL" -b release
        env:
          MAINURL: ${{ secrets.MAINURL }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: ytj/pubspec.yaml

      - run: flutter --version

      - name: Building IPA
        run: |
          cd ytj
          xcode-project use-profiles
          flutter build ios --release --no-codesign
          xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner --config Release
  #collect the files            
      # - name: collect ipa artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: adhoc-ipa
      #     # Path to the release files
      #     path: ytj/build/ios/ipa/*.ipa

