name: iOS Build WYS-USER

on:
  push:
    branches: [ "wys-user-ios" ]
  pull_request:
    branches: [ "wys-user-ios" ]

jobs:
  build:
    name: CI Build
    runs-on: macos-15

    steps:
## 
      - name: Select Xcode version
        run: "sudo xcode-select --switch /Applications/Xcode_16.3.app/Contents/Developer"

# 安装必要的依赖
      - name: Install python and codemagic tools
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'          

      - name: Install python dependencies
        run:  python -m pip install codemagic-cli-tools

# 设置SSH KEY
      - name: Setup SSH
        run: |
          mkdir -p "$HOME/.ssh"
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 "$HOME/.ssh/id_rsa"
          ssh-keyscan codeup.aliyun.com >> "$HOME/.ssh/known_hosts"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

# Clone Repo
      - name: Clone target repo
        run: git clone --recursive "$WYS_USER_URL" -b $WYS_USER_BRANCH
        env:
          WYS_USER_URL: ${{ secrets.WYS_USER_URL }}
          WYS_USER_BRANCH: ${{ secrets.WYS_USER_BRANCH }}


# 安装Flutter

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: wanyisheng/pubspec.yaml

      - run: flutter --version

# Build Flutter                        
      - name: Building IPA
        run: |
          cd wanyisheng/ios
          fastlane ios release_beta
        env:
          PUB_HOSTED_URL: https://pub.flutter-io.cn
          FLUTTER_STORAGE_BASE_URL: https://storage.flutter-io.cn
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_KEY_ID: ${{ secrets.AUTH_KEY_ID }}
          APP_STORE_ISSUER_ID: ${{ secrets.ISSUER_ID }}
          APP_STORE_PRIVATE_KEY: ${{ secrets.AUTH_KEY_BASE64 }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      # - name: Upload IPA Artifact
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ios-app
      #     path: ytj/ios/Runner.ipa