name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0

      - run: flutter --version

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          cat <<EOF > ~/.ssh/id_rsa
          $SSH_PRIVATE_KEY
          EOF
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan codeup.com >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone target repo
        run: git clone "$MAINURL"