name: android Build TMSH

on:
  push:
    branches: [ "tmsh-android" ]
  pull_request:
    branches: [ "tmsh-android" ]

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-latest

    steps:

# 设置SSH KEY
      - name: Setup SSH
        run: |
          mkdir -p "$HOME/.ssh"
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 "$HOME/.ssh/id_rsa"
          ssh-keyscan codeup.aliyun.com >> "$HOME/.ssh/known_hosts"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

# Clone Repo
      - name: Clone target repo
        run: git clone --recursive "$WYS_USER_URL" -b $WYS_USER_BRANCH
        env:
          WYS_USER_URL: ${{ secrets.WYS_USER_URL }}
          WYS_USER_BRANCH: ${{ secrets.WYS_USER_BRANCH }}


# 安装Flutter

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: wanyisheng/pubspec.yaml

      - run: flutter --version

# Build Flutter                        
      - name: Building APK
        run: |
          cd flutter build apk
        env:
          PUB_HOSTED_URL: https://pub.flutter-io.cn
          FLUTTER_STORAGE_BASE_URL: https://storage.flutter-io.cn
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      # - name: Upload IPA Artifact
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ios-app
      #     path: ytj/ios/Runner.ipa