name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Setup SSH
        run: |
          printf "%s" "$SSH_PRIVATE_KEY" > ~/id_rsa
          chmod 600 ~/id_rsa
          ssh-keyscan codeup.com >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone target repo
        run: git clone "$MAINURL"


      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0

      - run: flutter --version

