name: android Build TMSH

on:
  push:
    branches: [ "tmsh-android" ]
  pull_request:
    branches: [ "tmsh-android" ]

jobs:
  build:
    name: CI Build
    runs-on: macos-latest

    steps:

# 设置SSH KEY
      - name: Setup SSH
        run: |
          mkdir -p "$HOME/.ssh"
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 "$HOME/.ssh/id_rsa"
          ssh-keyscan codeup.aliyun.com >> "$HOME/.ssh/known_hosts"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

# Clone Repo
      - name: Clone target repo
        run: git clone --recursive "$MAINURL" -b $BRANCH
        env:
          MAINURL: ${{ secrets.MAINURL }}
          BRANCH: ${{ secrets.BRANCH }}


# 安装Flutter

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: ytj/pubspec.yaml

      - run: flutter --version

# Build Flutter                        
      - name: Building APK
        id: build_apk
        run: |
          cd ytj
          flutter build apk
          version_str=$(grep -m 1 -E '^version:' pubspec.yaml | sed 's/version: //; s/+/_/')
          apk_name="ytj_${version_str}.apk"
          echo "path=${apk_name}" >> $GITHUB_OUTPUT
          mv build/app/outputs/flutter-apk/app-release.apk ../${apk_name}
        env:
          PUB_HOSTED_URL: https://pub.flutter-io.cn
          FLUTTER_STORAGE_BASE_URL: https://storage.flutter-io.cn
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-beijing.aliyuncs.com"
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

      - run: ossutil cp -rf test.txt oss://bucket/path

      # - name: Upload to oss
      #   id: upload_to_oss
      #   uses: tvrcgo/oss-action@master
      #   with:
      #     key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
      #     key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      #     region: oss-cn-beijing
      #     bucket: ${{ secrets.OSS_BUCKET }}
      #     assets: |
      #       ${{ steps.build_apk.outputs.path }}:/app/ytj/

      # - name: Upload To OSS
      #   uses: taixw2/deploy-aliyun-oss@v1
      #   with:
      #     # aliyun config
      #     region: oss-cn-beijing.aliyuncs.com
      #     access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
      #     access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      #     bucket: ${{ secrets.OSS_BUCKET }}
      #     secure: true
      #     # deploy config
      #     entry: ${{ steps.build_apk.outputs.path }}
      #     remote-dir:  ${{ secrets.OSS_DIR }}