name: iOS Build TMSH

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: CI Build
    runs-on: macos-15

    steps:
## 选择Xcode的版本
      - name: Select Xcode version
        run: "sudo xcode-select --switch /Applications/Xcode_16.3.app/Contents/Developer"

# 安装必要的依赖
      - name: Install python and codemagic tools
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'          

      - name: Install python dependencies
        run:  python -m pip install codemagic-cli-tools

# 设置SSH KEY
      - name: Setup SSH
        run: |
          mkdir -p "$HOME/.ssh"
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 "$HOME/.ssh/id_rsa"
          ssh-keyscan codeup.aliyun.com >> "$HOME/.ssh/known_hosts"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

# Clone Repo
      - name: Clone target repo
        run: git clone --recursive "$MAINURL" -b $BRANCH
        env:
          MAINURL: ${{ secrets.MAINURL }}
          BRANCH: ${{ secrets.BRANCH }}



## 设置p8
      # - name: Get Certificate
      #   id: certFileDecodeP8
      #   uses: timheuer/base64-to-file@v1.0.3
      #   with:
      #     fileName: 'certificate.p12'
      #     encodedString: ${{ secrets.AUTH_KEY_BASE64 }}

      # - name: Copy Certificate
      #   run: |
      #     cp ${{ steps.certFileDecodeP8.outputs.filePath }} ytj/ios/fastlane/AuthKey.p8

## Setup Ruby and Bundle
      # - name: Set up Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: "2.7"
      # - name: Bundle install for iOS Gemfile
      #   timeout-minutes: 5
      #   run: cd ./ytj/ios && bundle install


# 安装Flutter

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: ytj/pubspec.yaml

      - run: flutter --version

# Build Flutter                          
      - name: Building IPA
        run: |
          cd ytj/ios
          fastlane ios release_beta
        env:
          PUB_HOSTED_URL: https://pub.flutter-io.cn
          FLUTTER_STORAGE_BASE_URL: https://storage.flutter-io.cn
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_KEY_ID: ${{ secrets.AUTH_KEY_ID }}
          APP_STORE_ISSUER_ID: ${{ secrets.ISSUER_ID }}
          APP_STORE_PRIVATE_KEY: ${{ secrets.AUTH_KEY_BASE64 }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Upload IPA Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: ytj/ios/Runner.ipa